server:
  port: 0
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     first: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: just-a-client



